Controllers/AnnounceController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.Remoting.Metadata.W3cXsd2001;
using System.Web;
using System.Web.Mvc;
using ESMB_Intl_Admin_FB.Models;


namespace ESMB_Intl_Admin_FB.Controllers
{
    public class AnnounceController : Controller
    {
        // GET
        public ActionResult Index()
        {
            if (Session["userCode"] == null)
            {
                return RedirectToAction("Login", "Login");
            }
            return View();
        }

        public ActionResult ViewAll()
        {
            return View(GetAllAnnouncements());
        }

        IEnumerable<TrueAnnouncement> GetAllAnnouncements()
        {
            using (var db = new TrueDBModel())
            {
                return db.TrueAnnouncements.Include(a => a.Author).ToList();
            }
        }

        public ActionResult AddOrEdit(int id = 0)
        {
            var anno = new TrueAnnouncement();
            if (id != 0)
            {
                using (TrueDBModel db = new TrueDBModel())
                {
                    anno = db.TrueAnnouncements.Where(x => x.AnnoID == id).FirstOrDefault<TrueAnnouncement>();
                }
            }

            return View(anno);
        }

        [HttpPost]

        public ActionResult AddOrEdit(TrueAnnouncement anno)
        {
            try
            {
                if (anno.ImageUpload != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(anno.ImageUpload.FileName);
                    string extension = Path.GetExtension(anno.ImageUpload.FileName);
                    fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;  //确保每个图片文件名唯一，避免上传相同文件
                    anno.ImgPath = "App_Files/Images/" + fileName;
                    anno.ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/App_Files/Images/"), fileName));
                }

                using (TrueDBModel db = new TrueDBModel())
                {
                    if (anno.AnnoID == 0)
                    {
                        db.TrueAnnouncements.Add(anno);
                        db.SaveChanges(); 
                    }
                    else
                    {
                        db.Entry(anno).State = EntityState.Modified;
                        db.SaveChanges();
                    }

                }

                //return RedirectToAction("ViewAll");
                return Json(new
                {
                    success = true,
                    html = GlobalClass.RenderRazorViewToString(this, "ViewAll", GetAllAnnouncements()),
                    message = "Submitted Successfully"
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                return Json(new
                {
                    success = false,
                    message = ex.Message
                }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Delete(int id)
        {
            try
            {
                using (TrueDBModel db = new TrueDBModel())
                {
                    TrueAnnouncement anno = db.TrueAnnouncements.Where(x => x.AnnoID == id).FirstOrDefault<TrueAnnouncement>();
                    db.TrueAnnouncements.Remove(anno);
                    db.SaveChanges();
                }
                return Json(new
                {
                    success = true,
                    html = GlobalClass.RenderRazorViewToString(this, "ViewAll", GetAllAnnouncements()),
                    message = "Delete Successfully"
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    success = false,
                    message = ex.Message
                }, JsonRequestBehavior.AllowGet);
            }
        }

        
    }
}

Views/Announce/AddOrEdit.cshtml
@model ESMB_Intl_Admin_FB.Models.TrueAnnouncement

@{
    ViewBag.Title = "AddOrEdit";
    //Layout = null;
}

@using (Html.BeginForm("AddOrEdit", "Announce", FormMethod.Post, new
{
    enctype = "multipart/form-data",
    onsubmit = "return jQueryAjaxPost(this);",
    data_restUrl = Url.Action("AddOrEdit", "Announce", new { id = 0 }),
    @class = "form-material m-t-25"
}))

{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @Html.HiddenFor(model => model.AnnoID)
    @Html.HiddenFor(model => model.ImgPath)
    <div class="row">
        <div class="col-md-7">
            <div class="form-group">
                @*<div class="col-md-12 m-b-20">
                    @Html.EditorFor(model => model.AuthorID, new { htmlAttributes = new { @class = "form-control", @placeholder = "AuthorID" } })
                    @Html.ValidationMessageFor(model => model.AuthorID, "", new { @class = "text-danger" })
                </div>*@

                <div class="col-md-12 m-b-20">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", @placeholder = "Announcement Title" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>

                <div class="col-md-12 m-b-20">
                    @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control", @rows = "5", @placeholder = "Announcement Text" } })
                    @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
                </div>

                <div class="col-md-12 m-b-10">
                    @Html.RadioButtonFor(model => model.Sender, "EMSB-Intl", new { @class = "check", @id = "square-radio-2", @name = "Sender", @checked = "checked", @data_radio = "iradio_square-blue" })
                    <label for="square-radio-2">Send as ESMB International</label>
                </div>

                <div class="col-md-12 m-b-30">
                    @Html.RadioButtonFor(model => model.Sender, "EMSB", new { @class = "check", @id = "square-radio-1", @name = "Sender", @data_radio = "iradio_square-blue" })
                    <label for="square-radio-1">Send as EMSB</label>
                </div>

                @{
                    string Now = DateTime.Now.ToString("yyMMddHHmm");
                    int NowInt = 0;
                    NowInt = Convert.ToInt32(Now);
                }

                @*While in 'Edit' Mode, keep the author name and created time as they are*@
                @if (Model.AnnoID != 0)
                {
                    @Html.EditorFor(model => model.AuthorID, new { htmlAttributes = new { @type = "hidden" } })
                    @Html.EditorFor(model => model.Added, new { htmlAttributes = new { @type = "hidden" } })
                }
                else
                {
                    @Html.TextBoxFor(model => model.AuthorID, new { @Value = @Session["userID"], @type = "hidden" })
                    @Html.TextBoxFor(model => model.Added, new { @Value = @NowInt, @type = "hidden" })

                }

                @Html.TextBoxFor(model => model.Updated, new { @Value = @NowInt, @type = "hidden" })

            </div>
        </div>
        <div class="col-md-5">
            <div class="form-group">
                <!-- Image drop zone-->
                <div class="col-md-12 m-b-40">
                    <label for="input-file-now">Add An Image Below (optional)</label>
                    <input type="file" id="input-file-now" class="dropify" name="ImageUpload" accept="image/jpg, image/png, image/jpeg" />
                </div>
                <!-- drop zone ends -->

                <div class="col-md-12 m-b-10">
                    @Html.RadioButtonFor(model => model.Status, "Drafted", new { @class = "check", @id = "square-radio-3", @name = "Status", @checked = "checked", @data_radio = "iradio_square-green" })
                    <label for="square-radio-3">Save as Draft</label>
                </div>
                <div class="col-md-12 m-b-30">
                    @Html.RadioButtonFor(model => model.Status, "Published", new { @class = "check", @id = "square-radio-4", @name = "Status", @data_radio = "iradio_square-red" })
                    <label for="square-radio-4">Publish Now</label>
                </div>
            </div>

        </div>
        <div class="col-md-12 m-b-20 text-right">
            <div class="form-group">
                @*While in 'Edit' Mode*@
                @if (Model.AnnoID != 0)
                {
                    <a class="btn btn-secondary waves-effect"
                       onclick="refreshAddNewTab('@Url.Action("AddOrEdit", "Announce", new {id = 0})', false)">
                        <i class="ti-plus"></i>&nbsp;Add New
                    </a>
                }
                <button type="submit" class="btn btn-danger waves-effect">Submit</button>
            </div>
        </div>
    </div>

}

Views/Announce/Index.cshtml
@using ESMB_Intl_Admin_FB.Models
@model dynamic
@{
    ViewBag.Title = "EMSB Intl Admin";
}

<!-- ============================================================== -->
<!-- Topbar header - style you can find in pages.scss -->
<!-- ============================================================== -->
<header class="topbar">
    <nav class="navbar top-navbar navbar-expand-md navbar-light">
        <!-- ============================================================== -->
        <!-- Logo -->
        <!-- ============================================================== -->
        <div class="navbar-header">
            <a class="navbar-brand" href="index.html">
                <!-- Logo icon --><b>
                    <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                    <!-- Dark Logo icon -->
                    <img src="~/App_Assets/images/logo-icon.png" alt="homepage" class="dark-logo" />

                </b>
                <!--End Logo icon -->
                <!-- Logo text --><span>
                    <!-- dark Logo text -->
                    <img src="~/App_Assets/images/logo-text.png" alt="homepage" class="dark-logo" />
                </span>
            </a>
        </div>
        <!-- ============================================================== -->
        <!-- End Logo -->
        <!-- ============================================================== -->
        <div class="navbar-collapse">
            <!-- ============================================================== -->
            <!-- toggle and nav items -->
            <!-- ============================================================== -->
            <ul class="navbar-nav mr-auto mt-md-0">
                <!-- This is  -->
                <li class="nav-item"><a class="nav-link nav-toggler hidden-md-up text-muted waves-effect waves-dark" href="javascript:void(0)"><i class="mdi mdi-menu"></i></a> </li>
                <li class="nav-item m-l-10"> <a class="nav-link sidebartoggler hidden-sm-down text-muted waves-effect waves-dark" href="javascript:void(0)"><i class="ti-menu"></i></a> </li>

            </ul>

        </div>
    </nav>
</header>
<!-- ============================================================== -->
<!-- End Topbar header -->
<!-- ============================================================== -->
<!-- ============================================================== -->
<!-- Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->
<aside class="left-sidebar">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- User profile -->
        <div class="user-profile">
            <!-- User profile image -->
            <div class="profile-img">
                <img src="~/App_Assets/images/users/profile.png" alt="user" />
                <!-- this is blinking heartbit-->
                @*<div class="notify setpos"> <span class="heartbit"></span> <span class="point"></span> </div>*@
            </div>
            <!-- User profile text-->
            <div class="profile-text">
                @{
                    if (@Session["userCode"] != null)
                    {
                        <h5>@Session["userName"]</h5>
                        if ((string)@Session["userLevel"] != "m")
                        {
                            <span class="badge badge-pill badge-info">Normal</span>
                        }
                        else
                        {
                            <span class="badge badge-pill badge-primary">Master</span>
                        }
                    }
                    else
                    {
                        <h5>Invalid User</h5>
                        <span class="badge badge-pill badge-danger">Access Denied</span>
                    }
                }
                <a href="@Url.Action("LogOut", "Login")" class="btn btn-link m-t-4" data-toggle="tooltip" title="Logout"><i class="fa fa-power-off"></i></a>
            </div>
        </div>
        <!-- End User profile text-->
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            @*id="sidebarnav"*@
            <ul class="text-center">
                <li class="nav-devider"></li>
                <li>
                    <a href="/announce" class="border-left border-secondary">
                        <i class="ti-save-alt"></i><b>ANNOUNCEMENTS</b>
                    </a>
                </li>
                @{
                    if ((string)@Session["userLevel"] == "m")
                    {
                        <li>
                            <a href="/author">
                                <i class="ti-direction"></i>ADMIN ACCOUNTS
                            </a>
                        </li>
                    }
                }

            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>
<!-- ============================================================== -->
<!-- End Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->
<!-- ============================================================== -->
<!-- Page wrapper  -->
<!-- ============================================================== -->
<div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="row page-titles">
        <div class="col-md-8 align-self-center">
            <h2 class="text-themecolor">EMSB International Dashboard</h2>
        </div>
        <div class="col-md-7 align-self-center">
            @*<ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                    <li class="breadcrumb-item">pages</li>
                    <li class="breadcrumb-item active">Table footable</li>
                </ol>*@
        </div>
        @*<div>  这个是右下角的 setting 动画转轮，和呼出侧边设置栏
                <button class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
            </div>*@
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <div class="row">
            <div class="col-12">

                <!-- Announcement card -->
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Create, Edit, Publish, and Delete Announcements</h4>
                        <h6 class="card-subtitle">You can choose to publish the announcements right after creating them or save them as drafts and edit later.</h6>

                        <ul class="nav nav-tabs profile-tab" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" data-toggle="tab" href="#allViewTab" role="tab">View All</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#newAnnoTab" role="tab">Add New</a>
                            </li>
                        </ul>

                        <div class="tab-content">
                            <div id="allViewTab" class="tab-pane active" role="tabpanel">
                                <!-- All Announcements Tab-->
                                @Html.Action("ViewAll")
                            </div>

                            <div id="newAnnoTab" class="tab-pane fade in p-t-20" role="tabpanel">
                                <!-- Edit & Add -->
                                @Html.Action("AddOrEdit")

                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
        <!-- Right sidebar -->
        <!-- ============================================================== -->
        <!-- .right-sidebar -->
        <div class="right-sidebar">
            <div class="slimscrollright">
                <div class="rpanel-title"> Service Panel <span><i class="ti-close right-side-toggle"></i></span> </div>
                <div class="r-panel-body">
                    <ul id="themecolors" class="m-t-20">
                        <li><b>With Light sidebar</b></li>
                        <li><a href="javascript:void(0)" data-theme="default" class="default-theme">1</a></li>
                        <li><a href="javascript:void(0)" data-theme="green" class="green-theme">2</a></li>
                        <li><a href="javascript:void(0)" data-theme="red" class="red-theme">3</a></li>
                        <li><a href="javascript:void(0)" data-theme="blue" class="blue-theme working">4</a></li>
                        <li><a href="javascript:void(0)" data-theme="purple" class="purple-theme">5</a></li>
                        <li><a href="javascript:void(0)" data-theme="megna" class="megna-theme">6</a></li>
                        <li class="d-block m-t-30"><b>With Dark sidebar</b></li>
                        <li><a href="javascript:void(0)" data-theme="default-dark" class="default-dark-theme">7</a></li>
                        <li><a href="javascript:void(0)" data-theme="green-dark" class="green-dark-theme">8</a></li>
                        <li><a href="javascript:void(0)" data-theme="red-dark" class="red-dark-theme">9</a></li>
                        <li><a href="javascript:void(0)" data-theme="blue-dark" class="blue-dark-theme">10</a></li>
                        <li><a href="javascript:void(0)" data-theme="purple-dark" class="purple-dark-theme">11</a></li>
                        <li><a href="javascript:void(0)" data-theme="megna-dark" class="megna-dark-theme ">12</a></li>
                    </ul>
                    <ul class="m-t-20 chatonline">
                        <li><b>Chat option</b></li>
                        <li>
                            <a href="javascript:void(0)"><img src="~/App_Assets/images/users/1.jpg" alt="user-img" class="img-circle"> <span>Varun Dhavan <small class="text-success">online</small></span></a>
                        </li>
                        <li>
                            <a href="javascript:void(0)"><img src="~/App_Assets/images/users/2.jpg" alt="user-img" class="img-circle"> <span>Genelia Deshmukh <small class="text-warning">Away</small></span></a>
                        </li>
                        <li>
                            <a href="javascript:void(0)"><img src="~/App_Assets/images/users/3.jpg" alt="user-img" class="img-circle"> <span>Ritesh Deshmukh <small class="text-danger">Busy</small></span></a>
                        </li>
                        <li>
                            <a href="javascript:void(0)"><img src="~/App_Assets/images/users/4.jpg" alt="user-img" class="img-circle"> <span>Arijit Sinh <small class="text-muted">Offline</small></span></a>
                        </li>
                        <li>
                            <a href="javascript:void(0)"><img src="~/App_Assets/images/users/5.jpg" alt="user-img" class="img-circle"> <span>Govinda Star <small class="text-success">online</small></span></a>
                        </li>
                        <li>
                            <a href="javascript:void(0)"><img src="~/App_Assets/images/users/6.jpg" alt="user-img" class="img-circle"> <span>John Abraham<small class="text-success">online</small></span></a>
                        </li>
                        <li>
                            <a href="javascript:void(0)"><img src="~/App_Assets/images/users/7.jpg" alt="user-img" class="img-circle"> <span>Hritik Roshan<small class="text-success">online</small></span></a>
                        </li>
                        <li>
                            <a href="javascript:void(0)"><img src="~/App_Assets/images/users/8.jpg" alt="user-img" class="img-circle"> <span>Pwandeep rajan <small class="text-success">online</small></span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Right sidebar -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
    <!-- footer -->
    <!-- ============================================================== -->
    <footer class="footer">
        © 2019 English Montreal School Board
    </footer>
    <!-- ============================================================== -->
    <!-- End footer -->
    <!-- ============================================================== -->
</div>
<!-- ============================================================== -->
<!-- End Page wrapper  -->